config/routes.rb
OngakuMusicServer::Application.routes.draw do

  resources :artists

  resources :albums

  resources :playlists
  resources :playlist_entries

  resources :songs do
    post 'rate_up'
    post 'rate_down'
    post 'set_tag'
    collection do
      get 'recent'
      get 'favorites'
      get 'new_placehold'
      get 'webcopy'
      post 'dowebcopy'
    end
  end

  namespace :system do
    get 'plugins'
    get 'license'
  end

  root :to => 'songs#index'

  Dir.glob File.expand_path("plugins/*", Rails.root) do |plugin_dir|
    file = File.join(plugin_dir, "config/routes.rb")
    if File.exists?(file)
      begin
        instance_eval File.read(file)
      rescue Exception => e
        puts "An error occurred while loading the routes definition of #{File.basename(plugin_dir)} plugin (#{file}): #{e.message}."
        exit 1
      end
    end
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name
  has_many :songs
  has_many :albums

  def Artist::garbage_collect()
    # Delete all artists that have no songs and no albums
    Artist.all.select {|artist| 
      artist.songs.count == 0 and artist.albums.count == 0
    }.each {|artist|
      puts "[DELETE] Artist:#{artist.name}"
      artist.delete
    }
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/_nav_top_heading.html.erb
<%= link_to "Artists", artists_path %>
<ul>
  <li><%= link_to 'New Artist', new_artist_path %></li>
</ul>

app/views/artists/edit.html.erb
<% @title = "Editing Artist #{@artist.name} %>
<% @page_actions = [
  lambda { link_to 'Show', @artist }
] %>

<%= render 'form' %>

app/views/artists/index.html.erb
<% @title = "Artists" %>

<table>
  <tr>
    <th>Name</th>
    <th>Songs</th>
    <td>Albums</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.sort_by {|artist| artist.name || "" }.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.songs.count %></td>
    <td><%= artist.albums.count %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/artists/new.html.erb
<% @title = "New Artist" %>

<%= render 'form' %>

app/views/artists/show.html.erb
<% @title = "Artist Information: #{@artist.name}" %>
<% @page_actions = [
  lambda { link_to 'Edit', edit_artist_path(@artist) }
] %>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<h1>Albums</h1>
<p>
  <ul>
  <% @artist.albums.select {|album| album.songs.count >= 1 }.sort_by {|album| album.title }.each do |album| %>
    <li><%= link_to album.title, album %>
  <% end %>
  </ul>
</p>

<h1>Songs</h1>
<%= render "songs/songlist", :songs => @artist.songs %>
<br/>