config/routes.rb
OngakuMusicServer::Application.routes.draw do

  resources :artists

  resources :albums

  resources :playlists
  resources :playlist_entries

  resources :songs do
    post 'rate_up'
    post 'rate_down'
    post 'set_tag'
    collection do
      get 'recent'
      get 'favorites'
      get 'new_placehold'
      get 'webcopy'
      post 'dowebcopy'
    end
  end

  namespace :system do
    get 'plugins'
    get 'license'
  end

  root :to => 'songs#index'

  Dir.glob File.expand_path("plugins/*", Rails.root) do |plugin_dir|
    file = File.join(plugin_dir, "config/routes.rb")
    if File.exists?(file)
      begin
        instance_eval File.read(file)
      rescue Exception => e
        puts "An error occurred while loading the routes definition of #{File.basename(plugin_dir)} plugin (#{file}): #{e.message}."
        exit 1
      end
    end
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :upload
  attr_accessible :album, :album_name
  attr_accessible :artist, :artist_name, :album_artist_name
  attr_accessible :name, :media_filename
  attr_accessible :track, :disk
  attr_accessible :origional_filename
  attr_accessible :license
  belongs_to :artist
  belongs_to :album

  def Song.find_with_tags( tags )
    where = Hash[ *tags.map {|k,v| [ :key, k, :value, v ] }.flatten ]
    Tag.where( where ).map {|tag| tag.song }
  end
  def Song.minimum_rating()
    @@minimum_rating ||= Song.minimum("rating")
  end
  def Song.maximum_rating()
    @@maximum_rating ||= Song.maximum("rating")
  end

  class TagProxy
    def initialize( song )
      @song = song
      @tag_cache = {}
      @dirty = {}
    end

    include Enumerable
    def each()
      Tag.where( :song_id => @song.id ).each {|tag|
        yield( tag.key, tag.value )
      }
    end

    def []( key )
      return @tag_cache[key] if @tag_cache.include?( key )

      @tag_cache[key] = Tag.where( :song_id => @song.id, :key => key ).first.value
    end
    def []=( key, value )
      @dirty[key] = true if @tag_cache[key] != value
      @tag_cache[key] = value

      @song.on_save {
        self.save!
      }
    end

    def save!()
      @dirty.each {|k,v|
        if( v == true )
          tag = Tag.where( :song_id => @song.id, :key => k ).first
          if !tag
            tag = Tag.new
            tag.song_id = @song.id
            tag.key = k
          end
          tag.value = @tag_cache[k]
          if tag.save!
            @dirty[k] = false
          end
        end
      }
    end

  end

  def tags()
    @tags_proxy ||= TagProxy.new(self)
  end

  def rating_percent()
    ( ( self.rating || 0 ).to_i - Song.minimum_rating ).to_f / ( Song.maximum_rating - Song.minimum_rating )
  end

  def artist_name=( artist_name )
    # Make sure leading and trailing whitespace doesn't create multiple copies of an artist
    artist_name ||= ""
    artist_name.gsub!(/^ */,'')
    artist_name.gsub!(/ *$/,'')

    # Make sure the ActiveRecord gets the artist name
    super

    # Update underlying field
    self.push_tags

    if !( ["",nil].include?( artist_name ) )
      # Perform a lookup in the artists to try and find an existing artist
      # with the name given
      artists = Artist.where( "name = ?", artist_name )

      # If there was no artist
      if( artists.size == 0 )
        # Go ahead and create one now
        artist = Artist.new({"name" => artist_name })
        @artist = artist
        self.on_save { @artist.save! }
      else
        # otherwise, use the first artist returned
        artist = artists[0]
      end

      # Update the artist field
      self.artist = artist

    end

    # Check to see if there is an album assigned to this artist
    if !self.album and self.album_name
      # Refresh the album name assignment
      self.album_name = self.album_name    
    end
  end
  def artist_name()
    if( self.artist )
      self.artist.name
    else
      super
    end
  end

  def album_name=( album_name )
    # Make sure leading and trailing whitespace doesn't create multiple copies of an album
    album_name ||= ""
    album_name.gsub!(/^ */,'')
    album_name.gsub!(/ *$/,'')

    # Make sure the ActiveRecord gets the album name
    super

    if( album_name == "" or !album_name )
      self.album = nil
      return
    end

    # Determine what to use for the album artist
    album_artist_name = self.album_artist_name || self.artist_name

    # Try to find the album artist
    album_artists = Artist.where( :name => album_artist_name )
    if( album_artists.size == 0 ) 
      # Create one if it does not exist
      album_artist = Artist.new( :name => album_artist_name )
      @album_artist = album_artist
      self.on_save { @album_artist.save! }
    else
      # Use the first entry if it does exist
      album_artist = album_artists[0]
    end

    # Try to find the album
    albums = Album.where( :title => album_name, :artist_id => album_artist )
    if( albums.size == 0 )
      album = Album.new({"title"=> album_name, "artist" => album_artist})
      @album = album
      self.on_save {|song| @album.save! }
    else
      album = albums[0]
    end

    # Update the album field
    self.album = album

    # Update underlying field
    self.push_tags
  end
  def album_name()
    if self.album
      self.album.title
    else
      super
    end
  end

  def media_path()
    File.join(Rails.root,"public","media",self.media_filename)
  end

  def upload=( upload )
    require 'taglib'

    # Get the extension of the uploaded file
    ext = File.extname( upload.original_filename )

    # Preserve the origional filename for later use in tagging
    self.original_filename = upload.original_filename

    # Generate a filename to store the media at
    random_filename = (0..32).map{ ('a'..'z').to_a[rand(26)] }.join + ext
    self.media_filename = random_filename

    # Write the media to disk
    File.open( media_path, "wb" ) {|f|
      f.write( upload.read )
    }

    # Extract tags
    self.pull_tags
  end

  def pull_tags()
    require 'taglib'

    # Extract tags from mp3 file
    TagLib::MPEG::File.open(media_path) do |fr|
      tag = fr.id3v2_tag

      # Capture the song title
      self.name = tag.title.chomp if tag.title

      # Capture the album artist name
      if frame = tag.frame_list('TPE2').first
        self.album_artist_name = frame.to_string
      end

      # Capture the disk number
      if frame = tag.frame_list('TPOS').first
        self.disk = frame.to_string.to_i
      end

      # Capture the song artist
      self.artist_name = tag.artist.chomp if tag.artist

      # Capture the album name
      self.album_name = tag.album.chomp if tag.album

      self.track = tag.track if tag.track
    end
  end
  def push_tags()
    return if !has_media?

    require 'taglib'

    # Store tags in MP3 file
    TagLib::MPEG::File.open(media_path) do |fr|
      tag = fr.id3v2_tag

      tag.title = self.name if self.name
      tag.artist = self.artist_name if self.artist_name
      tag.album = self.album_name if self.album_name
      tag.track = self.track  if self.track

      fr.save
    end
  end

  def id3_tags()
    return [] if !has_media?

    require 'taglib'

    res = []
    TagLib::MPEG::File.open( media_path ) do |fr|
      tag = fr.id3v2_tag
      tag.frame_list.each {|frame|
        res << [ frame.frame_id, frame.to_string ]
      }
    end

    return res
  end

  def has_media?()
    return self.media_filename && self.media_filename != ""
  end
  def destroy()
    super

    # Remove the file if it exists still
    if has_media?
      path = File.join(Rails.root,"public","media",self.media_filename)
      File.delete( path ) if File.exist?( path )
    end

    return true
  end

  def rate_up()
    self.rating = ( self.rating || 0 ) + 1
  end
  def rate_down()
    self.rating = ( self.rating || 0 ) - 1
  end

  def save!()
    super
    (@save_handlers||[]).each {|block| block.call }
  end
  def save()
    super
    (@save_handlers||[]).each {|block| block.call }
  end
  def on_save( &block )
    @save_handlers ||= []
    @save_handlers.push(block)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.find( :all, :order => 'artist_name' ).select

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
      format.m3u
    end
  end

  def stream
    @songs = Song.find( :all, :order => 'artist_name' )
  end

  def recent
    @songs = Song.where('').order('created_at').reverse_order.limit(20)

    respond_to do |format|
      format.html # recent.html.erb
      format.json { render json: @songs }
    end
  end
  def favorites
    mid_rating = ( Song.maximum("rating") - Song.minimum("rating") ) * 0.4 + Song.minimum("rating")
    @songs = Song.where('rating > ?',mid_rating).order('rating').reverse_order

    respond_to do |format|
      format.html # recent.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  def calc_recently_uploaded
    @recently_uploaded = Song.where('created_at >= ?',Time.new - 60*60*24).reverse
  end
  before_filter :calc_recently_uploaded, :only => [ :new, :new_placehold, :webcopy ]

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new_placehold
  def new_placehold
    @song = Song.new()
    @song.artist_name = params[:artist_name]
    @song.album_name = params[:album_name]
    @song.artist_name = @song.artist_name # HACK
    @song.album_name = @song.album_name   # HACK
    @song.name = params[:name]
    @song.track = params[:track]
    @song.disk = params[:disk]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs/1/rate_up
  def rate_up
    @song = Song.find(params[:song_id])
    @song.rate_up
    @song.save!

    respond_to do |format|
      format.json do
        render json: {
          :id => @song.id,
          :rating => @song.rating,
          :min => Song.minimum("rating"),
          :max => Song.maximum("rating"),
        }
      end
    end
  end

  # POST /songs/1/rate_down
  def rate_down
    @song = Song.find(params[:song_id])
    @song.rate_down
    @song.save!

    respond_to do |format|
      format.json do
        render json: {
          :id => @song.id,
          :rating => @song.rating,
          :min => Song.minimum("rating"),
          :max => Song.maximum("rating"),
        }
      end
    end
  end

  def set_tag
    @song = Song.find(params[:song_id])
    key = params[:key]
    value = params[:value]
    @song.tags[key] = value if key and value
    
    respond_to do |format|
      if @song.save
        format.json do
          render json: {
            :id => @song.id,
            :key => key,
            :value => value
          }
        end
        format.html do
          redirect_to @song, notice: "Song tag '#{key}' was set to '#{value}'"
        end
      end
    end
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    @song.artist_name = @song.artist_name # HACK
    @song.album_name = @song.album_name   # HACK

    respond_to do |format|
      if @song.save
        format.html { redirect_to new_song_path, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def webcopy
    @song = Song.new(params[:song])
    @recently_uploaded = Song.where('created_at >= ?',Time.new - 60*60*24).reverse
  end
  def dowebcopy
    url = params[:url]
    puts url.inspect
    Thread.new(url) {|url|
      begin
        require 'uri'

        u = URI.parse("#{[url].flatten.first}")
        puts "Webcopy: #{u}"
        res = Net::HTTP.start( u.host, u.port ) {|http|
          http.request( Net::HTTP::Get.new( u.path ) )
        }
        if "200" == res.code
          song = Song.new()
          song.upload = res.body
          song.original_filename = "#{u}"
          song.save!
        end
      rescue => e
        puts e
        puts e.backtrace
      end
    }
    redirect_to webcopy_songs_path
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  def rating( song )
    rate = ( song.rating || 0 ).to_i
    r = song.rating_percent * 5.0

    o = ""
    o << "<div id='song_#{song.id}_rating' class='song_rating'>"
    o << "<span class='stars'>"
    r.to_i.times do
      o << image_tag("star.png", :alt => "*", :size => "16x16")
    end
    o << "</span>"
    o << "(<span id='song_#{song.id}_rating_number' class='rating_number'>#{rate}</span>)"
    o << "</div>"
    return raw(o)
  end
  def rate_up( song )
    o = ""
    o << "<a onclick='$.ajax({"
    o <<   "url:\"#{song_rate_up_path(song, :format => :json)}\","
    o <<   "type: \"POST\","
    o <<   "success: update_rating,"
    o << "});return false;'>"
    o << image_tag("rate_up.png", :alt => "+", :size => "16x16")
    o << "</a>"
    return raw(o)
  end
  def rate_down( song )
    o = ""
    o << "<a onclick='$.ajax({"
    o <<   "url:\"#{song_rate_down_path(song, :format => :json)}\","
    o <<   "type: \"POST\","
    o <<   "success: update_rating,"
    o << "});return false;'>"
    o << image_tag("rate_down.png", :alt => "-", :size => "16x16")
    o << "</a>"
    return raw(o)
  end
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :upload, 'File' %>
    <%= f.file_field :upload %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_form2.html.erb
<%= form_for(@song, :url => { :action => :dowebcopy}) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= label :url, 'URL' %>
    <%= text_field :url %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_nav_top_heading.html.erb
<%= link_to "Songs", songs_path %>
<ul>
  <li><%= link_to "All", songs_path %></li>
  <li><%= link_to "Recent", recent_songs_path %></li>
  <li><%= link_to "Favorites", favorites_songs_path %></li>
  <li><%= link_to "Upload", new_song_path %></li>
  <li><%= link_to "Copy", webcopy_songs_path %></li>
  <li><%= link_to "Placeholder", new_placehold_songs_path %></li>
</ul>

app/views/songs/_songlist.html.erb
<table width=100%>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Artist</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% idx = 0 %>
<% songs.each_with_index do |song,i| %>
  <% if song.has_media? %>
    <tr class='songs <%= (i%2==0) ? "even-song" : "odd-song" %>' id='song_<%=idx%>'>
      <td class='c1'>
        <%= jplayer_play_index(idx) %>
        <% idx += 1 %>
  <% else %>
    <tr class='songs <%= (i%2==0) ? "even-song" : "odd-song" %>'>
      <td class='c1'>
  <% end %>
    </td>
    <td class='c2'><%= link_to song.name, song %></td>
    <td class='c3'><%= song_artist_link( song ) %></td>
    <td class='c4'><%= song_album_link( song ) %> (<%= song.disk ? "D#{song.disk}" : "" %>T<%=song.track%>)</td>
    <td class='c5'>&nbsp;</td>
    <td class='c6'><%= rating( song ) %></td>
    <td class='c7'><%= rate_up(song) %><br/><%= rate_down(song) %></td>
    <td class='c8'><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= render 'shared/player', :songlist => songs %>

app/views/songs/edit.html.erb
<% @title = "Edit #{@song.artist.name} - #{@song.name}" %>
<% @page_actions = [
  lambda { link_to 'Show', @song }
] %>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    Original filename: <%= @song.original_filename %>
  </p>

  <p>
    <%= f.label :name, "Song Title" %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :album_name, "Album" %>
    <%= f.text_field :album_name %>
  </p>
  <p>
    <%= f.label :artist_name, "Artist" %>
    <%= f.text_field :artist_name %>
  </p>
  <p>
    <%= f.label :track, "Track" %>
    <%= f.number_field :track %>
  </p>
  <p>
    <%= f.label :disk, "Disk" %>
    <%= f.number_field :disk %>
  </p>
  <p>
    <%= f.label :license, "License" %>
    <%= f.select( "license", options_for_select(Ongaku::License.list(), @song.license)) 
    %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/favorites.html.erb
<% @title = "Favorite Songs" %>

<%= render 'songlist', :songs => @songs %>

app/views/songs/index.html.erb
<% @title = "Song Library" %>

<%= render 'songlist', :songs => @songs %>

app/views/songs/index.m3u.erb
#EXTM3U
<% @songs.each {|song| %>
#EXTINF:400,<%= song.artist_name %> - <%= song.name %>
http://68.97.164.77:3000/media/<%= song.media_filename %>
<% } %>

app/views/songs/new.html.erb
<% @title = "New Song" %>

<%= render 'form' %>

<h1>Recently Uploaded Songs</h1>
<%= render "songlist", :songs => @recently_uploaded %>

app/views/songs/new_placehold.html.erb
<% @title = "Create Song Placeholder" %>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    Original filename: <%= @song.original_filename %>
  </p>

  <p>
    <%= f.label :name, "Song Title" %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :album_name, "Album" %>
    <%= f.text_field :album_name %>
  </p>
  <p>
    <%= f.label :artist_name, "Artist" %>
    <%= f.text_field :artist_name %>
  </p>
  <p>
    <%= f.label :track, "Track" %>
    <%= f.number_field :track %>
  </p>
  <p>
    <%= f.label :disk, "Disk" %>
    <%= f.number_field :disk %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/recent.html.erb
<% @title = "Recently Added Songs" %>

<%= render 'songlist', :songs => @songs %>

app/views/songs/show.html.erb
<% @title = "Song Data: #{@song.artist.name} - #{@song.name}" %>

<% code = capture do %>
  <% Playlist.all.each_with_index {|playlist,i| %>
    <form id='add_to_playlist_<%=i%>' method='post' action='<%= playlist_entries_path %>'>
      <input type='hidden' name='song_id' value='<%= @song.id %>' />
      <input type='hidden' name='playlist_id' value='<%= playlist.id %>' />
      <a href='#' onclick='$("#add_to_playlist_<%=i%>").submit()'>Add to <%= playlist.title %></a>
    </form>
  <% } %>
<% end %>

<% @page_actions = [
  lambda { link_to 'Edit', edit_song_path(@song) },
  :separator,
  lambda { code }
] %>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Artist:</b>
  <%= song_artist_link( @song ) %>
</p>

<p>
  <b>Album:</b>
  <%= song_album_link( @song ) %>
</p>

<p>
  <b>Album Artist:</b>
  <%= @song.album_artist_name %>
</p>

<p>
  <b>Download link:</b>
  <a href="/media/<%= @song.media_filename %>">file</a>
</p>

<p>
  <b>License:</b>
  <%= @song.license %>
</p>

<h2>Media Tags</h2>
<p>
  <ul>
  <% @song.id3_tags.each do |tag| %>
    <li><%= tag[0] %>: <%= tag[1] %></li>
  <% end %>
  </ul>
</p>

<h2>Ongaku Tags</h2>
<ul>
  <% @song.tags.to_a.sort.each {|key,value| %>
    <li><%= key %> = <%= value %></li>
  <% } %>
</ul>
<form id='add_tag' method='post' action='<%= song_set_tag_path(@song) %>'>
  <div class='float-left'>
    <b>Tag</b><br/>
    <td><input type='text' name='key' />
  </div>
  <div class='float-left'>
    <b>Value</b><br/>
    <input type='text' name='value' />
    <a href='#' onclick='$("#add_tag").submit();return false;'>Add Tag</a>
  </div>
</form>

<%= render_plugable( "songs/show" ) %>

<%= render "shared/player" %>

app/views/songs/stream.html.erb
<% @songs.each {|song| %>
  <%= link_to song.name, "/media/#{song.media_filename}" %><br/>
<% } %>

app/views/songs/webcopy.html.erb
<% @title = "Upload Song" %>

<%= form_for(@song, :url => { :action => "dowebcopy" } ) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= label :url, "URL" %>
    <%= text_field :url, "" %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h1>Recently Uploaded Songs</h1>
<%= render "songlist", :songs => @recently_uploaded %>