config/routes.rb
OngakuMusicServer::Application.routes.draw do

  resources :artists

  resources :albums

  resources :playlists
  resources :playlist_entries

  resources :songs do
    post 'rate_up'
    post 'rate_down'
    post 'set_tag'
    collection do
      get 'recent'
      get 'favorites'
      get 'new_placehold'
      get 'webcopy'
      post 'dowebcopy'
    end
  end

  namespace :system do
    get 'plugins'
    get 'license'
  end

  root :to => 'songs#index'

  Dir.glob File.expand_path("plugins/*", Rails.root) do |plugin_dir|
    file = File.join(plugin_dir, "config/routes.rb")
    if File.exists?(file)
      begin
        instance_eval File.read(file)
      rescue Exception => e
        puts "An error occurred while loading the routes definition of #{File.basename(plugin_dir)} plugin (#{file}): #{e.message}."
        exit 1
      end
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title
  attr_accessible :artist, :artist_id, :artist_name
  has_many :songs
  belongs_to :artist

  def artist_name()
    if self.artist
      self.artist.name
    else
      nil
    end
  end
  def artist_name=( name )
    self.artist = Artist.where( "name = ?", name ).first
  end
  def Album::garbage_collect()
    # Delete all albums that have no songs.  Note: this will grab albums that were manually created and have no placeholders
    Album.all.select {|album|
      album.songs.count == 0
    }.each {|album|
      puts "[DELETE] Album:#{ album.artist ? "#{album.artist.name} -" : "" }#{album.title}"
      album.delete
    }
  end
#  def artist=(name)
#    a = Artist.where( "name = ?", name )
#    if( a )
#      self.artist = a
#    end
#  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.find( :all, :order => :title )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end

    if params[:song_update]
      song = Song.new( {:id => params[:song_update] } )
      song.album = @album
      song.save!
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :value => params[:title] %>
  </div>
  <div class="field">
    <%= f.label :artist_name %><br />
    <%= f.number_field :artist_name, :value => params[:artist] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/_nav_top_heading.html.erb
<%= link_to "Albums", albums_path %>
<ul>
  <li><%= link_to "New Album", new_album_path %></li>
</ul>

app/views/albums/edit.html.erb
<% @title = "Edit #{@album.title}" %>
<% @page_actions = [
  lambda { link_to 'Show', @album },
]
%>

<%= render 'form' %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Songs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.title %></td>
    <% if album.artist %>
      <td><%= link_to album.artist.name, album.artist %></td>
    <% else %>
      <td>[ no artist ]</td>
    <% end %>
    <td><%= album.songs.size %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/albums/new.html.erb
<% @title = "Create New Album" %>

<%= render 'form' %>

app/views/albums/show.html.erb
<% 
  if @album.artist
    @title = "Album Information: #{@album.artist.name} - #{@album.title}"
  else 
    @title = "Album Information: #{@album.title}"
  end
  @page_actions = [
    lambda { link_to 'Edit', edit_album_path(@album) }
  ]
%>
<p>
  <b>Title:</b>
  <%= @album.title %>
</p>

<p>
  <b>Artist:</b>
  <% if @album.artist %>
    <%= link_to @album.artist.name, @album.artist %>
  <% end %>
</p>

<% songs = @album.songs.sort_by {|s| "%04i %04i" % [(s.disk||1),(s.track||9999)] } %>
<%= render 'songs/songlist', :songs => songs %>
<%= link_to 'Add placeholder', new_placehold_songs_path( 
  :artist_name => @album.artist ? @album.artist.name : "",
  :album_name => @album.title,
  :track => (@album.songs.map {|song| song.track || 0 }.reduce {|lhs,rhs| lhs > rhs ? lhs : rhs } || 0 ) + 1
) %>