config/routes.rb
OngakuMusicServer::Application.routes.draw do

  resources :artists

  resources :albums

  resources :playlists
  resources :playlist_entries

  resources :songs do
    post 'rate_up'
    post 'rate_down'
    post 'set_tag'
    collection do
      get 'recent'
      get 'favorites'
      get 'new_placehold'
      get 'webcopy'
      post 'dowebcopy'
    end
  end

  namespace :system do
    get 'plugins'
    get 'license'
  end

  root :to => 'songs#index'

  Dir.glob File.expand_path("plugins/*", Rails.root) do |plugin_dir|
    file = File.join(plugin_dir, "config/routes.rb")
    if File.exists?(file)
      begin
        instance_eval File.read(file)
      rescue Exception => e
        puts "An error occurred while loading the routes definition of #{File.basename(plugin_dir)} plugin (#{file}): #{e.message}."
        exit 1
      end
    end
  end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :title
  has_many :playlist_entries
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/_nav_top_heading.html.erb
<%= link_to "Playlists", playlists_path %>
<ul>
  <li><%= link_to 'New Playlist', new_playlist_path %></li>
</ul>

app/views/playlists/edit.html.erb
<% @title = "Edit Playlist" %>
<% @page_actions = [
  lambda { link_to 'Show', @playlist }
] %>
<h1>Editing playlist</h1>

<%= render 'form' %>

app/views/playlists/index.html.erb
<% @title = "Playlists" %>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.title %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/playlists/new.html.erb
<% @title = "Create New Playlist" %>

<%= render 'form' %>

app/views/playlists/show.html.erb
<% @title = "Playlist #{@playlist.title}" %>
<% @page_actions = [
  lambda { link_to 'Edit', edit_playlist_path(@playlist) }
] %>

<% songs = @playlist.playlist_entries.map {|entry| entry.song } %>
<%= render 'songs/songlist', :songs => songs %>